name: app
description: "Blue Light Filter App"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  blue_light_filter:
    path: ../blue_light_filter
  overlay_service: 
    path: ../overlay_service
  sqflite_db_common:
    path: ../../sqflite_db_common
  easy_localization: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/translations/
