name: blue_light_filter_main
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  blue_light_filter_core:
    path: ../blue_light_filter_core
  overlay_service: 
    path: ../overlay_service
  sqflite_db_common:
    path: ../../sqflite_db_common

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
